Copy hm-autoloader.php to mu-plugins if absent (#1511)
This change will break other Pressbooks plugins that load hm-autoloader.php in a phpunit bootstrap.php file

> Fatal error: Cannot declare class HM\Autoloader\Autoloader, because the name is already in use in /tmp/wordpress/wp-content/mu-plugins/hm-autoloader.php on line 5
> PHP Fatal error:  Cannot declare class HM\Autoloader\Autoloader, because the name is already in use in /tmp/wordpress/wp-content/mu-plugins/hm-autoloader.php on line 5


The reason is 1) the bootstrap file loads `/pressbooks/hm-autoloader.php` before 2) mu-plugins are loaded. Because the same code is loaded twice, from two different files, the second time it loads PHP dies.

The fix is to remove `hm-autoloader.php` from the bootstrap.php file

![culprits](https://user-images.githubusercontent.com/812192/49894479-061e7980-fe1c-11e8-945b-d4457de1ab5c.png)